testname: Polyphonic_TSM_Evaluation
testId: tsm_poly_alpha_test
bufferSize: 4096
stopOnErrors: true
showButtonPreviousPage: false

pages:
  - type: generic
    id: welcome_page
    name: Welcome
    content: "Thank you for participating! You will hear a reference audio track and several processed versions. Please rate the naturalness and quality of each track compared to the reference."

  - type: mushra
    id: trial_alpha_0_5
    name: "Test 1: Speeding Up (Alpha = 0.5)"
    content: "Please rate the quality of these tracks. The speed is doubled (alpha = 0.5). Focus on the preservation of musical rhythm and transients."
    showDetails: false
    reference: ref.wav
    stimuli:
      ref: reference.wav
      anchor: anchor_3.5.wav
      sola: SOLA_0.5.wav
      pv: PV_0.5.wav

  - type: mushra
    id: trial_alpha_1_5
    name: "Test 2: Slowing Down (Alpha = 1.5)"
    content: "Please rate the quality of these tracks. The speed is slowed down (alpha = 1.5). Focus on harmonic continuity and absence of echoes."
    showDetails: false
    reference: ref.wav
    stimuli:
      ref: reference.wav
      anchor: anchor_3.5.wav
      sola: SOLA_1.5.wav
      pv: PV_1.5.wav

  - type: finish
    id: finish_page
    name: Finish
    content: "The test is successfully completed. Please click the download button to save your results file (.csv) and send it to the researcher. Thank you!"